### ISSUE TITLE
Application run failed

### ISSUE THREAD

**Issue by osan463** [eccenca/braine#1]
Environment:
- ubuntu 21.10
- jdk: openjdk 17.0.2

Build:
```
mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.eccenca:braine-webclient >--------------------
[INFO] Building BRAINE Webclient 0.0.1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ braine-webclient ---
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ braine-webclient ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ braine-webclient ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 33 source files to /opt/asidees/repos/braine/eccenca/webclient/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ braine-webclient ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /opt/asidees/repos/braine/eccenca/webclient/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ braine-webclient ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /opt/asidees/repos/braine/eccenca/webclient/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ braine-webclient ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running DockerTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in DockerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-war-plugin:3.3.1:war (default-war) @ braine-webclient ---
[INFO] Packaging webapp
[INFO] Assembling webapp [braine-webclient] in [/opt/asidees/repos/braine/eccenca/webclient/target/braine-webclient-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [/opt/asidees/repos/braine/eccenca/webclient/src/main/webapp]
[INFO] Building war: /opt/asidees/repos/braine/eccenca/webclient/target/braine-webclient-0.0.1-SNAPSHOT.war
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.5.3:repackage (repackage) @ braine-webclient ---
[INFO] Replacing main artifact with repackaged archive
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.5.3:repackage (default) @ braine-webclient ---
[INFO] Replacing main artifact with repackaged archive
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ braine-webclient ---
[INFO] Installing /opt/asidees/repos/braine/eccenca/webclient/target/braine-webclient-0.0.1-SNAPSHOT.war to /home/osan/.m2/repository/com/eccenca/braine-webclient/0.0.1-SNAPSHOT/braine-webclient-0.0.1-SNAPSHOT.war
[INFO] Installing /opt/asidees/repos/braine/eccenca/webclient/pom.xml to /home/osan/.m2/repository/com/eccenca/braine-webclient/0.0.1-SNAPSHOT/braine-webclient-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.618 s
[INFO] Finished at: 2022-03-10T18:55:19+04:00
[INFO] ------------------------------------------------------------------------

```

Run:
```
java -jar ./braine-webclient-0.0.1-SNAPSHOT.war 
  _______       ______        ________       ________      ___   __       ______      
/_______/\     /_____/\      /_______/\     /_______/\    /__/\ /__/\    /_____/\     
\::: _  \ \    \:::_ \ \     \::: _  \ \    \__.::._\/    \::\_\\  \ \   \::::_\/_    
 \::(_)  \/_    \:(_) ) )_    \::(_)  \ \      \::\ \      \:. `-\  \ \   \:\/___/\   
  \::  _  \ \    \: __ `\ \    \:: __  \ \     _\::\ \__    \:. _    \ \   \::___\/_  
   \::(_)  \ \    \ \ `\ \ \    \:.\ \  \ \   /__\::\__/\    \. \`-\  \ \   \:\____/\ 
    \_______\/     \_\/ \_\/     \__\/\__\/   \________\/     \__\/ \__\/    \_____\/ 
                                                                                      
BRAINE-Storm a Cloud Service Manager 0.0.1-beta
Powered by http://eccenca.com
2022-03-10 18:55:40.491  INFO 1106928 --- [           main] com.eccenca.braine.BraineWebApp          : Starting BraineWebApp v0.0.1-SNAPSHOT using Java 17.0.2 on osan-desktop with PID 1106928 (/opt/asidees/repos/braine/eccenca/webclient/target/braine-webclient-0.0.1-SNAPSHOT.war started by osan in /opt/asidees/repos/braine/eccenca/webclient/target)
2022-03-10 18:55:40.495  INFO 1106928 --- [           main] com.eccenca.braine.BraineWebApp          : No active profile set, falling back to default profiles: default
2022-03-10 18:55:41.900  INFO 1106928 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 7070 (http)
2022-03-10 18:55:41.915  INFO 1106928 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-03-10 18:55:41.915  INFO 1106928 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.50]
2022-03-10 18:55:48.019  INFO 1106928 --- [           main] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2022-03-10 18:55:48.447  INFO 1106928 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-03-10 18:55:48.447  INFO 1106928 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7850 ms
2022-03-10 18:55:48.547  INFO 1106928 --- [           main] j.e.resource.webcontainer.jsf.config     : Initializing Mojarra 2.2.20 ( 20190731-0757 59754ac80c05d61848a08939ddd11a324f2345ac) for context ''
2022-03-10 18:55:49.216  INFO 1106928 --- [           main] j.e.r.webcontainer.jsf.application       : JSF1048: PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked with these annotations will have said annotations processed.
2022-03-10 18:55:50.379  INFO 1106928 --- [           main] .w.PostConstructApplicationEventListener : Running on PrimeFaces 11.0.0
2022-03-10 18:55:51.831  WARN 1106928 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imageRegistryView': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
2022-03-10 18:55:51.834  INFO 1106928 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-03-10 18:55:51.838  WARN 1106928 --- [           main] j.e.resource.webcontainer.jsf.config     : Unexpected state during contextDestroyed: no ConfigManager instance in current ServletContext but one is expected to exist.
2022-03-10 18:55:51.865  INFO 1106928 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-10 18:55:51.893 ERROR 1106928 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imageRegistryView': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.9.jar!/:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.9.jar!/:5.3.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.3.jar!/:2.5.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.3.jar!/:2.5.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.3.jar!/:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.3.jar!/:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.3.jar!/:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.3.jar!/:2.5.3]
	at com.eccenca.braine.BraineWebApp.main(BraineWebApp.java:19) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[braine-webclient-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[braine-webclient-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[braine-webclient-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) ~[braine-webclient-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
Caused by: java.lang.ExceptionInInitializerError: null
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:82) ~[jena-arq-4.3.2.jar!/:4.3.2]
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56) ~[jena-arq-4.3.2.jar!/:4.3.2]
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:44) ~[jena-arq-4.3.2.jar!/:4.3.2]
	at com.eccenca.braine.jena.core.RDFLinkHTTP.queryExec(RDFLinkHTTP.java:87) ~[classes!/:0.0.1-SNAPSHOT]
	at com.eccenca.braine.jena.core.RDFLinkHTTP.query(RDFLinkHTTP.java:68) ~[classes!/:0.0.1-SNAPSHOT]
	at org.apache.jena.rdflink.RDFConnectionAdapter.query(RDFConnectionAdapter.java:105) ~[jena-rdfconnection-4.3.2.jar!/:4.3.2]
	at com.eccenca.braine.dao.SPARQLService.query(SPARQLService.java:95) ~[classes!/:0.0.1-SNAPSHOT]
	at com.eccenca.braine.dao.SPARQLService.list(SPARQLService.java:112) ~[classes!/:0.0.1-SNAPSHOT]
	at com.eccenca.braine.dao.ImageRegistryService.list(ImageRegistryService.java:29) ~[classes!/:0.0.1-SNAPSHOT]
	at com.eccenca.braine.view.ImageRegistryView.init(ImageRegistryView.java:62) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.9.jar!/:5.3.9]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.9.jar!/:5.3.9]
	... 26 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @68fb2c38
	at org.aksw.jena_sparql_api.mapper.proxy.MapperProxyUtils.createProxyFactory(MapperProxyUtils.java:1403) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.createImplementation(JenaPluginUtils.java:219) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.createImplementation(JenaPluginUtils.java:205) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.registerResourceClass(JenaPluginUtils.java:258) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.registerResourceClass(JenaPluginUtils.java:237) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.registerResourceClasses(JenaPluginUtils.java:179) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.JenaPluginUtils.registerResourceClasses(JenaPluginUtils.java:174) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.core.plugin.JenaPluginJsaCore.init(JenaPluginJsaCore.java:22) ~[jena-sparql-api-core-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.core.plugin.JenaPluginJsaCore.start(JenaPluginJsaCore.java:14) ~[jena-sparql-api-core-3.17.0-1.jar!/:na]
	at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117) ~[jena-base-4.3.2.jar!/:4.3.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193) ~[jena-base-4.3.2.jar!/:4.3.2]
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169) ~[jena-base-4.3.2.jar!/:4.3.2]
	at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115) ~[jena-base-4.3.2.jar!/:4.3.2]
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88) ~[jena-core-4.3.2.jar!/:4.3.2]
	at org.apache.jena.query.Query.<clinit>(Query.java:64) ~[jena-arq-4.3.2.jar!/:4.3.2]
	... 43 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @68fb2c38
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[na:na]
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[na:na]
	at org.aksw.jena_sparql_api.mapper.proxy.MapperProxyUtils.proxyDefaultMethod(MapperProxyUtils.java:2048) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	at org.aksw.jena_sparql_api.mapper.proxy.MapperProxyUtils.createProxyFactory(MapperProxyUtils.java:1401) ~[jena-sparql-api-mapper-proxy-3.17.0-1.jar!/:na]
	... 58 common frames omitted

```

**Comment by edgardmarx** [comment]
Dear @osan463 ,

Thanks for the bug report, have you tried to add user and password as instructed at the repository README file?

`$target % java -jar -Dserver.port=7070 -Dclient.oauth.user=<user> -Dclient.oauth.password=<password> `

**Comment by osan463** [comment]
Dear @edgardmarx , I'm added them to application.properties file. Also I'm added it into launch string too. Result the same.

**Comment by edgardmarx** [comment]
Thanks @osan463,

Would you mind to check if you are able to reach the BRAINE portal?

`curl --head braine.eccenca.dev`

**Comment by osan463** [comment]
@edgardmarx, the problem were in jdk version. Error occurs when using jdk-17. With jdk-11 and 15 it seems ok. Works. Thanks.

**Comment by edgardmarx** [comment]
thnks, I will let it open till I can investigate and/or fix it.
It seems to be a Jena incompatibility problem by looking at the logs.
